<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Expenses Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
            padding: 0;
        }
        .header p {
            margin: 5px 0 0 0;
            padding: 0;
        }
        .filters {
            margin-bottom: 15px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .filters p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #dee2e6;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .summary {
            margin-top: 20px;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .summary h3 {
            margin-top: 0;
            font-size: 16px;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Expenses Report</h1>
        <p>Generated on: {{ now()->format('F j, Y h:i A') }}</p>
    </div>

    @if(isset($filters) && (isset($filters['start_date']) || isset($filters['end_date']) || isset($filters['supplier'])))
    <div class="filters">
        <h3>Filters Applied:</h3>
        @if(isset($filters['start_date']))
            <p><strong>From:</strong> {{ \Carbon\Carbon::parse($filters['start_date'])->format('M d, Y') }}</p>
        @endif
        @if(isset($filters['end_date']))
            <p><strong>To:</strong> {{ \Carbon\Carbon::parse($filters['end_date'])->format('M d, Y') }}</p>
        @endif
        @if(isset($filters['supplier']))
            <p><strong>Expense Title:</strong> {{ $filters['supplier'] }}</p>
        @endif
    </div>
    @endif

    @if($expenses->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>S/N</th>
                    <th>Date</th>
                    <th>Expense Title</th>
                    <th>Amount</th>
                    <th>Recorded By</th>
                </tr>
            </thead>
            <tbody>
                @foreach($expenses as $index => $expense)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $expense->created_at->format('M d, Y') }}</td>
                        <td>{{ $expense->name }}</td>
                        <td>₦{{ number_format($expense->amount, 2) }}</td>
                        <td>{{ $expense->user->name }}</td>
                    </tr>
                @endforeach
                <tr>
                    <td colspan="3" class="text-right font-bold">Total:</td>
                    <td class="font-bold">₦{{ number_format($expenses->sum('amount'), 2) }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    @else
        <p>No expenses found for the selected filters.</p>
    @endif

    <div class="footer">
        <p>Generated by {{ config('app.name') }} • Page <span class="pageNumber"></span> of <span class="totalPages"></span></p>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 10;
            $font = $fontMetrics->getFont("DejaVu Sans");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 35;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>
</html>
